# Generated by Django 5.0.2 on 2024-03-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, default='images/default_image.jpg', max_length=255, upload_to='images/')),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
