# Generated by Django 5.0.2 on 2024-04-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_presentation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Presentation',
            new_name='Presentations',
        ),
    ]
