# Generated by Django 5.0.2 on 2024-04-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_rename_presentation_presentations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentation.presentations')),
            ],
        ),
    ]
