# Generated by Django 5.0.2 on 2024-04-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0005_remove_zlide_presentation_zlide_presentation_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presentations',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
